spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loupitchoun?useSSL=false
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      fail-on-empty-beans: "false"
      write-dates-as-timestamps: "false"
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

security:
  basic:
    enabled: false

token:
  secret: zezerferggersegrrgg36543543654